### ISSUE TITLE
Migrate away from google.com GCP project google-containers

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#1571]
Part of umbrella issue to migrate away from google.com gcp projects: https://github.com/kubernetes/k8s.io/issues/1469

This GCP project has historically hosted the kubernetes project's artifacts in GCR and GCS.

Suggested path forward:
- [x] migrate away from gcr.io/google-containers
  - [x] use k8s.gcr.io instead of gcr.io/google-containers (https://github.com/kubernetes/release/issues/270)
  - [x] ensure artifact promotion is fully supported by sig-release (https://github.com/kubernetes/k8s.io/issues/157#issuecomment-721397190)
- [x] deprecate and migrate away from gs://kubernetes-release-dev and gcr.io/kubernetes-ci-images (https://github.com/kubernetes/k8s.io/issues/2318)
- [x] depercate and migrate away from gs://kubernetes-release - binaries (e.g. tar.gz artifacts listed in kubernetes/kubernetes CHANGELOG) - https://github.com/kubernetes/k8s.io/issues/2396
- [x] identify any remaining service accounts / IAM permissions that the project uses

/wg k8s-infra
/sig release
/area release-eng
/area artifacts

/milestone v1.21
I doubt we'll have this completely addressed within v1.21, but I'd like to see us make progress on some of the individual pieces.

**Comment by spiffxp** [comment]
Here's traffic in terms of bytes sent for the artifacts that are currently community-hosted (k8s.gcr.io, gs://k8s-artifacts-prod). This exclude staging projects.
![Screen Shot 2021-08-04 at 9 30 45 AM](https://user-images.githubusercontent.com/49258/128224152-5346bec0-73b4-49ad-9e12-30ce7530f51b.png)

Here's traffic in terms of bytes sent for gs://kubernetes-release (and its regional buckets), which has yet to be migrated
![Screen Shot 2021-08-04 at 9 32 40 AM](https://user-images.githubusercontent.com/49258/128224174-4b390baf-7463-4989-b360-f9046f86e3f8.png)

**Comment by BenTheElder** [comment]
On the google side: further restricted access to this but left a temporary carve-out to keep publishing releases until https://github.com/kubernetes/k8s.io/issues/2396 is resolved

**Comment by BenTheElder** [comment]
Sent cl/707294470 internally to drop remaining Kubernetes project service account access and make what's left here ~read-only.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/release/issues/3425 is not this project, but related.

Otherwise this is ~done. Downstream users will still take time to migrate (... like https://github.com/cncf/k8s-conformance/pull/3512) but over time as they desire currently releases they'll naturally move to dl.k8s.io (and already had to for some time for registry.k8s.io).
