### ISSUE TITLE
[Umbrella Issue] Project artifact management task list

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/k8s.io#170]
This is an umbrella issue covering the tasks needed to manage, distribute and promote container images. Once this issue is complete people will have a single URL that they can use to pull each image no matter where they are in the world. Projects will have a known way to push and promote their images.

Tasks:
- [ ] Design Document describing how all this will work.
- [ ] GCR Repository for official published images
- [ ] GCR Repository for projects to use (#158)
- [ ] GCS Bucket for projects to use (#153)
- [ ] Process for image promotion (#157)
- [ ] ECR Repository mirror for Amazon
- [ ] ACR Repository mirror for Azure
- [ ] HTTP Redirector for image and artifact renaming.

**Comment by spiffxp** [comment]
/remove-help
I don't think this is appropriately scoped for help wanted

/priority important-longterm
Very important for the longterm health of this project.  We've migrated image hosting (k8s.gcr.io), but we haven't migrated binary artifact hosting (dl.k8s.io).  So we're not all the way done and already hosting/serving artifacts is a very non-trivial amount of our spend  We will need to start the conversation back up on mirroring.

**Comment by spiffxp** [comment]
Issue covers too much, should break into:
- k8s.gcr.io mirroring
- binary artifact promotion
- artifact mirroring

Can close once those are created

**Comment by justaugustus** [comment]
Will be covered as part of the SIG Release Artifact Mgmt epic: https://github.com/kubernetes/sig-release/issues/1372
I'll close this out once I've captured everything that was in this issue.

/assign
/milestone v1.21

**Comment by justaugustus** [comment]
Captured Aaron's asks in https://github.com/kubernetes/sig-release/issues/1372#issuecomment-766241874.

/close
