### ISSUE TITLE
Migrate away from google.com gcp project kubernetes-scale

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#2241]
Related:
- Part of umbrella issue to migrate away from google.com gcp projects: https://github.com/kubernetes/k8s.io/issues/1469
- Part of: https://github.com/kubernetes/perf-tests/issues/1898

Umbrella issue for migrating or removing dependence on the kubernetes-scale project.  [cs.k8s.io results](https://cs.k8s.io/?q=kubernetes-scale&i=nope&files=&excludeFiles=&repos=) show that:
- it's used for our 5k node scalability tests, specifically
  - [ci-kubernetes-e2e-gce-scale-correctness](https://github.com/kubernetes/test-infra/blob/4cade9cb253cecc44ba1c8945251440d87b07511/config/jobs/kubernetes/sig-scalability/sig-scalability-release-blocking-jobs.yaml#L4)
  - [ci-kubernetes-e2e-gce-scale-performance](https://github.com/kubernetes/test-infra/blob/4cade9cb253cecc44ba1c8945251440d87b07511/config/jobs/kubernetes/sig-scalability/sig-scalability-release-blocking-jobs.yaml#L57)
- these jobs also log to `gs://sig-scalability-logs` which lives under `kubernetes-jenkins` 

We should:

- [X] stand up an equivalent (singular) project in k8s-infra : https://github.com/kubernetes/k8s.io/pull/2195
- [x] determine what quota is needed for it : https://github.com/kubernetes/k8s.io/issues/2225
- [x] request the quota : https://github.com/kubernetes/k8s.io/issues/2225
- [X] setup an equivalent bucket for logs in k8s-infra : #2240
- [X] setup and run canary jobs: https://github.com/kubernetes/test-infra/pull/22430
- [x] drop the canary job / switch the live job for ci-kubernetes-e2e-scale-correctness: https://github.com/kubernetes/test-infra/pull/24080)
- [x] drop the canary job / switch the live job for ci-kubernetes-e2e-scale-performance: https://github.com/kubernetes/test-infra/pull/23807

/assign @ameukam 
It turns out Arnaud has done a fair amount of this, but I just realized we never had an umbrella issue to tie it to the project we're working to replace.  I'll link / edit what's been done so far

/priority important-soon
/wg k8s-infra
/sig scalability
/sig release
since these are release-informing but treated as release-blocking jobs
/sig testing

**Comment by spiffxp** [comment]
/milestone v1.22
I'm not quite sure it's reasonable to expect we can flip this in time for Test Freeze, but we want this ready by the time the next cycle starts

**Comment by ameukam** [comment]
Some issues about the canary jobs: 

- `ci-kubernetes-e2e-gce-scale-correctness-canary` requests compute resources superior to what the build clusters can offer. We may need adjust those requests. 
-  I see failures about gce instance access in `ci-kubernetes-kubemark-gce-scale-canary`, `ci-kubernetes-e2e-gce-scale-performance-canary` and `ci-kubernetes-kubemark-gce-scale-scheduler-canary`. I'll enable [OS Login](https://cloud.google.com/compute/docs/instances/managing-instance-access#enable_oslogin) for `k8s-infra-scale-e2e-5k-project` project.

**Comment by ameukam** [comment]
In the 2021-07-22 meeting of SIG-Scalability, @wojtek-t suggested to increase the gcp nodes to 5k for the optional presubmits. I will : 
- add a canary job for `pull-kubernetes-e2e-gce-large-performance`.
- increase the quotas of CPU and persistent disks on `k8s-infra-scale-e2e-5k-project`.

**Comment by ameukam** [comment]
@marseel @tosi3k You can use this issue as a reference for any progress made for the job migration.

**Comment by spiffxp** [comment]
Look at job configs in kubernetes/test-infra, I see that `ci-kubernetes-e2e-gce-scale-performance` has been migrated away, but ci-kubernetes-e2e-gce-scale-correctness` has not.  Any particular reason why?

**Comment by spiffxp** [comment]
/close
Correctness was flipped over 7 days ago: https://github.com/kubernetes/test-infra/pull/24080

Calling this done.  Great work @ameukam !
