### ISSUE TITLE
[Umbrella issue] Building AWS infrastructure for registry.k8s.io

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#3568]
Part of:
   - #3411
   
Follow up of:
  - https://github.com/kubernetes-sigs/oci-proxy/issues/22
  
Following AWS folx: https://github.com/kubernetes-sigs/oci-proxy/issues/22#issuecomment-1084011545.

The AWS infrastructure will mainly serve as a hosting environment for image layers of the container images produced by the Kubernetes Project. We should:

- [x] Get the list of AWS buckets where we want to replicate the image layers : https://github.com/kubernetes-sigs/oci-proxy/issues/38#issuecomment-1085369923
- [x] https://github.com/kubernetes/k8s.io/issues/3595
- [ ] Create a IAM role with permissions to write to the buckets
- [x] Create a user with access keys using the IAM role
   - From https://kubernetes.slack.com/archives/CCK68P2Q2/p1650407982934869. Created in https://github.com/cncf-infra/aws-infra
   - https://github.com/cncf-infra/aws-infra/pull/15

**Comment by ameukam** [comment]
cc @dims @jaypipes 

cc @kubernetes/release-engineering 

/kind feature
/area artifacts
/area infra
/area release-eng
/sig release

/milestone v1.24

**Comment by hh** [comment]
Closing https://github.com/kubernetes/k8s.io/issues/3541 in favour of this new ticket.

but bringing some of the conversation forward:

> Is there an agreed upon naming scheme?

I know that @eddiezane had reserved some buckets at some point @jaypipes. Might look into that, and how we might extend it to have -REGION or similar.

**Comment by hh** [comment]
From the #k8s-infra-meeting yesterday:

> AI : Create iam-role / CNCF specific for publication, the only thing with write permissions to these buckets. `k8s-infra-writer`

**Comment by ameukam** [comment]
IMHO we should try to follow some aspects of the infrastructure created for @kubernetes/release-engineering: https://github.com/kubernetes/sig-release/blob/master/release-engineering/gcp.md #release-engineering .

- Reuse the [created](https://github.com/cncf/credits/issues/1) account where we will do active development taking into consideration https://github.com/kubernetes-sigs/promo-tools/issues/533 and can optionally be leveraged for e2e testing. It is not necessary to create one bucket per region; a single bucket per continent (asia, eu, us) would be enough for now.
- Create a new production-only AWS account with only the buckets, roles, and groups required to host the container images. Only AWS organization administrators should access this account.

**Comment by Riaankl** [comment]
The PR address the teraform of S3 buckets. 
https://github.com/kubernetes/k8s.io/pull/3605

**Comment by hh** [comment]
I thought Jay had decided on a list of about 10 regions?

Also, let's ensure we put forward a similar document to https://github.com/kubernetes/sig-release/blob/master/release-engineering/gcp.md #release-engineering in the coming weeks.

**Comment by BobyMCbobs** [comment]
> [ ] Create a IAM role with permissions to write to the buckets

@ameukam, this was completed some time ago 
https://github.com/cncf-infra/aws-infra/pull/10

> [ ] Create a user with access keys using the IAM role

we are using federated identity for authenticating
https://github.com/cncf-infra/aws-infra/pull/15

**Comment by Riaankl** [comment]
Thanks @BobyMCbobs 
@ameukam look like this is done. Should we close the issue of are there more TOD's to add to the issue?
