### ISSUE TITLE
Tracking 73 Kubernetes AWS Account Migrations from CNCF

### ISSUE THREAD

**Issue by hh** [kubernetes/k8s.io#4626]
There are 73 total Kubernetes accounts in the CNCF AWS Account. We will need to track these migrations.

arn:aws:servicequotas:::organizations/L-29A0C5DF is a request to raise the default max accounts from 10 to 200.

The process for moving accounts between organisations is outlined here: https://aws.amazon.com/premiumsupport/knowledge-center/organizations-move-accounts/

# Kubernetes OU (3)

-   [x] sig-infra-aws-admins+accounts@kubernetes.io (previously: k8s-infra-accounts@kubernetes.io)
-   [x] sig-release-leads@kubernetes.io (password shared with @ cpanato)
-   [x] k8s-infra-aws-root-account@kubernetes.io (password known by @ameukam and @dims)
- [registry.k8s.io OU (1)](#org817d4e3)
  - [aws-ebs-csi-driver OU (1)](#orgb7326f2)
  - [kops OU (4)](#orgc496c06)
  - [sig-k8s-infra OU (12)](#org25da404)
  - [capa OU (52)](#orgbead97b)

<a id="org817d4e3"></a>

# registry.k8s.io OU (1)

-   [x] k8s-infra-aws-admins+registry-k8s-io@kubernetes.io (previously k8s-infra-aws-registry-k8s-io-admin@kubernetes.io)

<a id="orgb7326f2"></a>

# aws-ebs-csi-driver OU (1)

-   [x] aws-ebs-csi-driver@lists.cncf.io

<a id="orgc496c06"></a>

# kops OU (4)

-   [x] k8s-infra-aws-admins+e2e-kops-2020-03-15-c@kubernetes.io
-   [x] k8s-infra-aws-admins+e2e-kops-2020-03-15-d@kubernetes.io
-   [x] k8s-infra-aws-admins+e2e-kops-2020-03-15-a@kubernetes.io
-   [x] k8s-infra-aws-admins+e2e-kops-2020-03-15-b@kubernetes.io

<a id="org25da404"></a>

# sig-k8s-infra OU (12)

-   [x] k8s-infra-aws-admins+image2020111905@kubernetes.io
-   [x] k8s-infra-aws-admins+image2020111904@kubernetes.io
-   [x] k8s-infra-aws-admins+image2020111906@kubernetes.io
-   [x] k8s-infra-aws-admins+image2020111907@kubernetes.io
-   [x] k8s-infra-aws-admins+image2020111909@kubernetes.io
-   [x] k8s-infra-aws-admins+image2021032801@kubernetes.io
-   [x] k8s-infra-aws-admins+image2020111902@kubernetes.io
-   [x] k8s-infra-aws-admins+image20212503/28/2101@kubernetes.io
-   [x] k8s-infra-aws-admins+image2020111910@kubernetes.io
-   [x] k8s-infra-aws-admins+image2020111908@kubernetes.io
-   [x] k8s-infra-aws-admins+image2020111903@kubernetes.io
-   [x] k8s-infra-aws-admins+image2020111900@kubernetes.io

<a id="orgbead97b"></a>

# capa OU (52)

-   [x] cncf-k8s-infra-aws-capa-ami@lists.cncf.io
-   [x] cncf-k8s-infra-aws-capa-demo@lists.cncf.io
-   [x] k8s-infra-aws-admins+capa-2020-07-12-01@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-2020-07-12-02@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-2020-07-13-00@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-2020-07-13-01@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-2020-07-13-02@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-2020-07-13-03@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-2020-07-13-04@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-2020-07-13-05@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-2020-07-13-06@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-2020-07-13-07@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-2020-07-13-08@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-2020-07-13-09@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-2020-07-13-10@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-2020-07-13-11@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-2020-07-13-12@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-2020-07-13-13@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-account-00@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-account-01@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-account-02@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-account-03@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-account-04@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-account-05@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-account-06@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-account-07@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-account-08@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-account-09@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-account-2020-02-18-a@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-account-2020-02-18-b@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-account-2020-02-18-c@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-account-2020-02-18-d@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-account-2020-02-18-e@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-account-2020-02-18-f@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-account-2020-02-18-g@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-account-2020-02-18-h@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-account-2020-02-18-i@kubernetes.io
-   [x] k8s-infra-aws-admins+capa-account-2020-02-18-j@kubernetes.io
-   [x] k8s-infra-aws-admins+capa2020111900@kubernetes.io
-   [x] k8s-infra-aws-admins+capa2020111901@kubernetes.io
-   [x] k8s-infra-aws-admins+capa2020111902@kubernetes.io
-   [x] k8s-infra-aws-admins+capa2020111903@kubernetes.io
-   [x] k8s-infra-aws-admins+capa2020111904@kubernetes.io
-   [x] k8s-infra-aws-admins+capa2020111905@kubernetes.io
-   [x] k8s-infra-aws-admins+capa2020111906@kubernetes.io
-   [x] k8s-infra-aws-admins+capa2020111907@kubernetes.io
-   [x] k8s-infra-aws-admins+capa2020111908@kubernetes.io
-   [x] k8s-infra-aws-admins+capa2020111909@kubernetes.io
-   [x] k8s-infra-aws-admins+capa2020111910@kubernetes.io
-   [x] k8s-infra-aws-admins+capa2020111911@kubernetes.io
-   [x] k8s-infra-aws-admins+capa2020111912@kubernetes.io
-   [x] k8s-infra-aws-admins+capa2020111913@kubernetes.io

**Comment by hh** [comment]
When planning your migration, we need to consider the following:

- [ ] You have a valid payment method on the member account to address any charges that are incurred while the accounts are migrating.
I've opened Case ID: 11777279581 with AWS to research, but I'm trying to avoid doing this by hand. Suggestions and workarounds welcome here.

- [ ]  Before migrating, consider the number of accounts in your organization. If an increase is needed, see [Quotas for AWS Organizations](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_reference_limits.html) for more information.
I've submitted this, waiting on resolution. No update to arn:aws:servicequotas:::organizations/L-29A0C5DF yet.

- [ ] You backed up any reports from the member accounts that you need to keep. The member accounts can't access these reports after leaving the Organization.
@dims @ameukam Let me know of any to migrate here.

**Comment by hh** [comment]
From https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_accounts_remove.html#orgs_manage_accounts_remove-from-master
### Effects of removing an account from an organization
When you remove an account from an organization, no direct changes are made to the account. However, the following indirect effects occur:
- [ ] The account is now responsible for paying its own charges and must have a valid payment method attached to the account.
I'm working on this now, trying to find some automation.
- [ ] Integration with other services might be disabled. If you remove an account from an organization that has integration with an AWS service enabled, the users in that account can no longer use that service.
I'm not aware of any, but there just wanted this highlighted.

**Comment by hh** [comment]
It looks like we will need to detach each of the 73 accounts from the CNCF org, and at the moment I disconnect them we will need to provide credit card details (which can only be done via the Web Console / UI).

While I can do that, an account can only be part of a single org. So once detached, each of the accounts will need to be authenticated to to accept the invitation to join the new Kubernetes org.

It's unclear to me the best way to handle authenticating to these accounts as the passwords are likely handled in a distributed way by the Kubernetes community.

**Comment by hh** [comment]
I'm looking at options for authenticating to and accepting the handshake to join the new org once they are detached from the CNCF org.

We must authenticate as each account, and AssumeRole doesn't look like it will work once the accounts are standalone. Also the current passwords are unknown to the CNCF at an administrative level.

We'll need to decide on a process. We could reset the password on each account as we go and share each of them with #sig-k8s-infra, but I'm open to options.

I've thought about trying it for one of the top level accounts that is less used, like `k8s-infra-accounts@kubernetes.io` to test the process, but wanted to get buy-in for the reset password approach OR possibly escalating a ticket with Premium Support with AWS.

/cc @dims @ameukam

**Comment by dims** [comment]
@hh will let @ameukam reply on the "try with top level account". If we can escalate a ticket, we should just start that without delay.

**Comment by hh** [comment]
@dims can you help to escalate this Case ID : 11777279581 ?
Our official support plan is Basic, so I'm not sure I can do much on my end:
https://support.console.aws.amazon.com/support/home?region=us-west-2#/case/?displayId=11777279581&language=en

**Comment by hh** [comment]
I'll work with @jeefy and @taylorwaggoner to get billing/card details to use during the migration. Once I have those we can try to move `k8s-infra-accounts@kubernetes.io` manually.

## Steps:
- [ ] Reset passwords for each account we migrate, or at least ensure Kubernetes access to the account without the CNCF Org (@hh / @ameukam)
  - We will need to authenticate directly without CNCF or Kubernetes Org access.
  - We should probably reset them all?
- [ ] CNCF Provides credit card details in order to make account standalone (@hh) **[aws organizations remove-account-from-organization --account-id](https://docs.aws.amazon.com/cli/latest/reference/organizations/remove-account-from-organization.html)** or via the Console
- [ ] Kubernetes Org admin issues (@hh / @ameukam) **[aws organizations invite-account-to-organization](https://docs.aws.amazon.com/cli/latest/reference/organizations/invite-account-to-organization.html)** capturing the handshake id
- [ ] Migrating Account authenticates via password or console to (@ameukam) **[aws organizations accept-handshake](https://docs.aws.amazon.com/cli/latest/reference/organizations/accept-handshake.html)**

**Comment by upodroid** [comment]
It is worth finding out if we need to retain most of these accounts. Are these accounts actually holding live infra or is it part of CI/CD usage like boskos projects? If they are part of a CI process and we can supply new accounts, we can provision fresh ones, reconfigure IAM, and use that opportunity to start on a clean slate.

**Comment by hh** [comment]
> It is worth finding out if we need to retain most of these accounts.
@upodroid I agree

> Are these accounts actually holding live infra or is it part of CI/CD usage like boskos projects? 
Is there anyone who could identify these easily given the list? I have some automation ready to go through them, but we need a plan, it's a lot of accounts.

> are they part of a CI process?
This migration is an ideal time to identify and consolidate.

I would suggest we add someone (or a role) from sig-k8s-infra to each of these accounts / mailing lists, so password resets can occur.

The Kubernetes OU is limited to accounts that contain k8s in the email:

`aws organizations list-accounts --query 'sort_by(Accounts,&Email)[?contains(Email,`k8s`)==`true`].[Email]' | grep \" | wc -l`
>  73

All but four of these are email lists maintained by kubernetes.io (google workspace groups / email lists?):
`aws organizations list-accounts --query 'sort_by(Accounts,&Email)[?contains(Email,`k8s`)==`true`].[Email]' | grep \" | grep -v kubernetes.io;

```
        "cncf-k8s-external-dns-aws@lists.cncf.io"
        "cncf-k8s-infra-aws-capa-ami@lists.cncf.io"
        "cncf-k8s-infra-aws-capa-demo@lists.cncf.io"
        "cncf-k8s-minikube-aws@lists.cncf.io"
```

**Comment by upodroid** [comment]
Getting access to the *@kubernetes.io emails is easy. 

Add your email to the groups in this file. Ignore everything between the + and @ symbols to get the email.

https://github.com/kubernetes/k8s.io/blob/main/groups/sig-k8s-infra/groups.yaml#L270

**Comment by ameukam** [comment]
We need to move the AWS accounts under those emails:

- [k8s-infra-aws-root-account@kubernetes.io](mailto:k8s-infra-aws-root-account@kubernetes.io)
- [k8s-infra-accounts@kubernetes.io](mailto:k8s-infra-accounts@kubernetes.io)
- [k8s-infra-aws-registry-k8s-io-admin@kubernetes.io](mailto:k8s-infra-aws-registry-k8s-io-admin@kubernetes.io)

we can revisit migration of the accounts used by Kops and CAPA.

**Comment by ameukam** [comment]
> It is worth finding out if we need to retain most of these accounts. Are these accounts actually holding live infra or is it part of CI/CD usage like boskos projects? If they are part of a CI process and we can supply new accounts, we can provision fresh ones, reconfigure IAM, and use that opportunity to start on a clean slate.

I'm in favor of this approach. we can have a mix of accounts created and accounts migrated.

**Comment by hh** [comment]
Regarding account limit quota increase request, there was an update:
```
Service: AWS Organizations
Region: US East (Northern Virginia)
Limit name: Default maximum number of accounts
New limit value: 200

For a quota increase of this type, I will need to collaborate with our service team to get approval.

The team can take anything between 24-48 hours to provide feedback to the request, this is to ensure that we can meet your needs while keeping existing infrastructure safe.

I have marked the request as a priority in order to get feedback as soon as possible.
```

**Comment by ameukam** [comment]
@hh Sent an invite for `k8s-infra-root-acocunt@kubernetes.io` account. Can you talk a look in the org handshakes in the CNCF org:

```bash
$ aws organizations invite-account-to-organization --target Id=REDACTED,Type=ACCOUNT
{
    "Handshake": {
        "Id": "h-8201bc74bc5846f480ea2e63bed0b7dc",
        "Arn": "arn:aws:organizations::REDACTED:handshake/o-kz4vlkihvy/invite/h-8201bc74bc5846f480ea2e63bed0b7dc",
        "Parties": [
            {
                "Id": "kz4vlkihvy",
                "Type": "ORGANIZATION"
            },
            {
                "Id": "REDACTED",
                "Type": "ACCOUNT"
            }
        ],
        "State": "OPEN",
        "RequestedTimestamp": "2023-01-18T20:43:46.778000+00:00",
        "ExpirationTimestamp": "2023-02-02T20:43:46.778000+00:00",
        "Action": "INVITE",
        "Resources": [
            {
                "Value": "o-kz4vlkihvy",
                "Type": "ORGANIZATION",
                "Resources": [
                    {
                        "Value": "kubernetes-aws-admins@lists.cncf.io",
                        "Type": "MASTER_EMAIL"
                    },
                    {
                        "Value": "Kubernetes AWS Admins",
                        "Type": "MASTER_NAME"
                    },
                    {
                        "Value": "ALL",
                        "Type": "ORGANIZATION_FEATURE_SET"
                    }
                ]
            },
            {
                "Value": "REDACTED",
                "Type": "ACCOUNT"
            }
        ]
    }
}
```

**Comment by hh** [comment]
[sig-release-leads@kubernetes.io](mailto:sig-release-leads@kubernetes.io) is now migrated

**Comment by hh** [comment]
[sig-infra-aws-admins+accounts@kubernetes.io](mailto:sig-infra-aws-admins+accounts@kubernetes.io) (previously: [k8s-infra-accounts@kubernetes.io](mailto:k8s-infra-accounts@kubernetes.io)) is now migrated

**Comment by hh** [comment]
[k8s-infra-aws-admins+registry-k8s-io@kubernetes.io](mailto:k8s-infra-aws-admins+registry-k8s-io@kubernetes.io) (previously [k8s-infra-aws-registry-k8s-io-admin@kubernetes.io](mailto:k8s-infra-aws-registry-k8s-io-admin@kubernetes.io)) has an updated email and is ready to migrate: @ameukam I'd like to do this one synchronously

I'd like to get @Riaankl to migrate the remaining accounts *@lists.cncf.io and k8s-infra-aws-admins+*kubernetes.io. The migration process is a bit more streamlined when we have access to everything now.

**Comment by hh** [comment]
@mrbobbytables: We will be generated a lot of passwords that need to be saved and likely access by #sig-k8s-infra and the sigs these are assigned to. @dims mentioned there is a community 1Password account we should be using. Do you have details?

**Comment by hh** [comment]
All but three accounts migrated. Will work to put passwords into 1Password next week.

**Comment by Riaankl** [comment]
Only account remaining to be migrated is `aws-ebs-csi-driver@lists.cncf.io`
We do not get the password reset email & link.
@ameukam @dims do you have access to that?

**Comment by dims** [comment]
@Riaankl check with CNCF folks like Amye? if we can figure out who is on that list, we can coordinate with them

**Comment by Riaankl** [comment]
> @Riaankl check with CNCF folks like Amye? if we can figure out who is on that list, we can coordinate with them

Will do.

**Comment by Riaankl** [comment]
> @Riaankl check with CNCF folks like Amye? if we can figure out who is on that list, we can coordinate with them

Got that sorted, last account migrated!

**Comment by ameukam** [comment]
> > @Riaankl check with CNCF folks like Amye? if we can figure out who is on that list, we can coordinate with them
> 
> Got that sorted, last account migrated!

@Riaankl if everything is done here, do you mind close this issue ? cc @jeefy @hh

**Comment by Riaankl** [comment]
@ameukam I still need to add the passwords for all the accounts in 1password
Think we can close after that. Thanks

**Comment by Riaankl** [comment]
All passowrds for the accounts that I migrated was added to the 1password vault AWS CI Accouts 
@hh @jeefy @ameukam 

/close

**Comment by hh** [comment]
```bash
aws organizations describe-organization
```

```bash
{
    "Organization": {
        "Id": "o-kz4vlkihvy",
        "Arn": "arn:aws:organizations::348685125169:organization/o-kz4vlkihvy",
        "FeatureSet": "ALL",
        "MasterAccountArn": "arn:aws:organizations::348685125169:account/o-kz4vlkihvy/348685125169",
        "MasterAccountId": "348685125169",
        "MasterAccountEmail": "kubernetes-aws-admins@lists.cncf.io",
        "AvailablePolicyTypes": [
            {
                "Type": "SERVICE_CONTROL_POLICY",
                "Status": "ENABLED"
            }
        ]
    }
}
```

```bash
aws organizations list-accounts | jq -r '.Accounts[] | select(.Status="ACTIVE") | .Name + " : " + .Email'  | sort
```

```bash
Kubernetes AWS Admins : kubernetes-aws-admins@lists.cncf.io
aws-ebs-csi-driver Infra : aws-ebs-csi-driver@lists.cncf.io
capa-2020-07-12-01 : k8s-infra-aws-admins+capa-2020-07-12-01@kubernetes.io
capa-2020-07-12-02 : k8s-infra-aws-admins+capa-2020-07-12-02@kubernetes.io
capa-2020-07-13-00 : k8s-infra-aws-admins+capa-2020-07-13-00@kubernetes.io
capa-2020-07-13-01 : k8s-infra-aws-admins+capa-2020-07-13-01@kubernetes.io
capa-2020-07-13-02 : k8s-infra-aws-admins+capa-2020-07-13-02@kubernetes.io
capa-2020-07-13-03 : k8s-infra-aws-admins+capa-2020-07-13-03@kubernetes.io
capa-2020-07-13-04 : k8s-infra-aws-admins+capa-2020-07-13-04@kubernetes.io
capa-2020-07-13-05 : k8s-infra-aws-admins+capa-2020-07-13-05@kubernetes.io
capa-2020-07-13-06 : k8s-infra-aws-admins+capa-2020-07-13-06@kubernetes.io
capa-2020-07-13-07 : k8s-infra-aws-admins+capa-2020-07-13-07@kubernetes.io
capa-2020-07-13-08 : k8s-infra-aws-admins+capa-2020-07-13-08@kubernetes.io
capa-2020-07-13-09 : k8s-infra-aws-admins+capa-2020-07-13-09@kubernetes.io
capa-2020-07-13-10 : k8s-infra-aws-admins+capa-2020-07-13-10@kubernetes.io
capa-2020-07-13-11 : k8s-infra-aws-admins+capa-2020-07-13-11@kubernetes.io
capa-2020-07-13-12 : k8s-infra-aws-admins+capa-2020-07-13-12@kubernetes.io
capa-2020-07-13-13 : k8s-infra-aws-admins+capa-2020-07-13-13@kubernetes.io
capa-2020-11-19-00 : k8s-infra-aws-admins+capa2020111900@kubernetes.io
capa-2020-11-19-01 : k8s-infra-aws-admins+capa2020111901@kubernetes.io
capa-2020-11-19-02 : k8s-infra-aws-admins+capa2020111902@kubernetes.io
capa-2020-11-19-03 : k8s-infra-aws-admins+capa2020111903@kubernetes.io
capa-2020-11-19-04 : k8s-infra-aws-admins+capa2020111904@kubernetes.io
capa-2020-11-19-05 : k8s-infra-aws-admins+capa2020111905@kubernetes.io
capa-2020-11-19-06 : k8s-infra-aws-admins+capa2020111906@kubernetes.io
capa-2020-11-19-07 : k8s-infra-aws-admins+capa2020111907@kubernetes.io
capa-2020-11-19-08 : k8s-infra-aws-admins+capa2020111908@kubernetes.io
capa-2020-11-19-09 : k8s-infra-aws-admins+capa2020111909@kubernetes.io
capa-2020-11-19-10 : k8s-infra-aws-admins+capa2020111910@kubernetes.io
capa-2020-11-19-11 : k8s-infra-aws-admins+capa2020111911@kubernetes.io
capa-2020-11-19-12 : k8s-infra-aws-admins+capa2020111912@kubernetes.io
capa-2020-11-19-13 : k8s-infra-aws-admins+capa2020111913@kubernetes.io
capa-account-00 : k8s-infra-aws-admins+capa-account-00@kubernetes.io
capa-account-01 : k8s-infra-aws-admins+capa-account-01@kubernetes.io
capa-account-02 : k8s-infra-aws-admins+capa-account-02@kubernetes.io
capa-account-03 : k8s-infra-aws-admins+capa-account-03@kubernetes.io
capa-account-04 : k8s-infra-aws-admins+capa-account-04@kubernetes.io
capa-account-05 : k8s-infra-aws-admins+capa-account-05@kubernetes.io
capa-account-06 : k8s-infra-aws-admins+capa-account-06@kubernetes.io
capa-account-07 : k8s-infra-aws-admins+capa-account-07@kubernetes.io
capa-account-08 : k8s-infra-aws-admins+capa-account-08@kubernetes.io
capa-account-09 : k8s-infra-aws-admins+capa-account-09@kubernetes.io
capa-account-2020-02-18-a : k8s-infra-aws-admins+capa-account-2020-02-18-a@kubernetes.io
capa-account-2020-02-18-b : k8s-infra-aws-admins+capa-account-2020-02-18-b@kubernetes.io
capa-account-2020-02-18-c : k8s-infra-aws-admins+capa-account-2020-02-18-c@kubernetes.io
capa-account-2020-02-18-d : k8s-infra-aws-admins+capa-account-2020-02-18-d@kubernetes.io
capa-account-2020-02-18-e : k8s-infra-aws-admins+capa-account-2020-02-18-e@kubernetes.io
capa-account-2020-02-18-f : k8s-infra-aws-admins+capa-account-2020-02-18-f@kubernetes.io
capa-account-2020-02-18-g : k8s-infra-aws-admins+capa-account-2020-02-18-g@kubernetes.io
capa-account-2020-02-18-h : k8s-infra-aws-admins+capa-account-2020-02-18-h@kubernetes.io
capa-account-2020-02-18-i : k8s-infra-aws-admins+capa-account-2020-02-18-i@kubernetes.io
capa-account-2020-02-18-j : k8s-infra-aws-admins+capa-account-2020-02-18-j@kubernetes.io
cncf-k8s-infra-aws-capa-ami : cncf-k8s-infra-aws-capa-ami@lists.cncf.io
cncf-k8s-infra-aws-capa-demo : cncf-k8s-infra-aws-capa-demo@lists.cncf.io
e2e-kops-2020-03-15-a : k8s-infra-aws-admins+e2e-kops-2020-03-15-a@kubernetes.io
e2e-kops-2020-03-15-b : k8s-infra-aws-admins+e2e-kops-2020-03-15-b@kubernetes.io
e2e-kops-2020-03-15-c : k8s-infra-aws-admins+e2e-kops-2020-03-15-c@kubernetes.io
e2e-kops-2020-03-15-d : k8s-infra-aws-admins+e2e-kops-2020-03-15-d@kubernetes.io
image-builder-aws-2020-11-19-00 : k8s-infra-aws-admins+image2020111900@kubernetes.io
image-builder-aws-2020-11-19-02 : k8s-infra-aws-admins+image2020111902@kubernetes.io
image-builder-aws-2020-11-19-03 : k8s-infra-aws-admins+image2020111903@kubernetes.io
image-builder-aws-2020-11-19-04 : k8s-infra-aws-admins+image2020111904@kubernetes.io
image-builder-aws-2020-11-19-05 : k8s-infra-aws-admins+image2020111905@kubernetes.io
image-builder-aws-2020-11-19-06 : k8s-infra-aws-admins+image2020111906@kubernetes.io
image-builder-aws-2020-11-19-07 : k8s-infra-aws-admins+image2020111907@kubernetes.io
image-builder-aws-2020-11-19-08 : k8s-infra-aws-admins+image2020111908@kubernetes.io
image-builder-aws-2020-11-19-09 : k8s-infra-aws-admins+image2020111909@kubernetes.io
image-builder-aws-2020-11-19-10 : k8s-infra-aws-admins+image2020111910@kubernetes.io
image-builder-aws-2021-03-28-01 : k8s-infra-aws-admins+image2021032801@kubernetes.io
image-builder-aws-2021-25-03/28/21-01 : k8s-infra-aws-admins+image20212503/28/2101@kubernetes.io
k8s-infra-artifacts-k8s-io-prod : k8s-infra-aws-admins+artifacts-k8s-io-prod@kubernetes.io
k8s-infra-aws-admins+accounts : k8s-infra-aws-admins+accounts@kubernetes.io
k8s-infra-aws-admins+registry-k8s-io : k8s-infra-aws-admins+registry-k8s-io@kubernetes.io
k8s-infra-aws-root-account : k8s-infra-aws-root-account@kubernetes.io
k8s-infra-networking : k8s-infra-aws-admins+infra-networking@kubernetes.io
k8s-infra-organisation-incident-response : k8s-infra-aws-admins+incident-response@kubernetes.io
k8s-infra-organisation-logging : k8s-infra-aws-admins+logging@kubernetes.io
k8s-infra-organisation-security : k8s-infra-aws-admins+security@kubernetes.io
k8s-infra-registry-k8s-io-prod : k8s-infra-aws-admins+registry-k8s-io-prod@kubernetes.io
k8s-infra-security-audit : k8s-infra-aws-admins+security-audit@kubernetes.io
k8s-infra-security-engineering : k8s-infra-aws-admins+security-engineering@kubernetes.io
k8s-infra-security-incident-response : k8s-infra-aws-admins+security-incident-response@kubernetes.io
k8s-infra-security-logs : k8s-infra-aws-admins+artifacts-k8S-io@kubernetes.io
k8s-infra-security-logs : k8s-infra-aws-admins+security-logs@kubernetes.io
k8s-infra-shared-services : k8s-infra-aws-admins+infra-network@kubernetes.io
k8s-infra-shared-services : k8s-infra-aws-admins+infra-shared-services@kubernetes.io
sig-release-leads : sig-release-leads@kubernetes.io
```

**Comment by jeefy** [comment]
Looks like some were missed, filed https://github.com/kubernetes/k8s.io/issues/5111 to capture that effort, but linking here as well.
