### ISSUE TITLE
[Umbrella Issue] Migrate CNCF Ecosystem projects from k8s.gcr.io to registry.k8s.io

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/k8s.io#4780]
With the [change to defaulting](https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/) to registry.k8s.io as our image registry and the [planned freeze in April](https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/), downstream projects in the CNCF ecosystem will likely be impacted. 

Currently 71 of the CNCF projects contain references to k8s.gcr.io, there seems to be a wide mix of usage from docs, to base images and CI.

Below is a list of projects that were surfaced in a "dumb" search for k8s.gcr.io, there may be valid references or false positives and they should be checked more closely and updated where possible.

**Projects**
 - [ ] [Aeraki Mesh](https://github.com/aeraki-mesh) | [search query](https://github.com/search?q=org%3Aaeraki-mesh%20%22k8s.gcr.io%22&type=code)
 - [ ] [Akri](https://github.com/deislabs) | [search query](https://github.com/search?q=org%3Adeislabs%20%22k8s.gcr.io%22&type=code)
 - [ ] [Antrea](https://github.com/antrea-io) | [search query](https://github.com/search?q=org%3Aantrea-io%20%22k8s.gcr.io%22&type=code)
 - [ ] [Argo](https://github.com/argoproj) | [search query](https://github.com/search?q=org%3Aargoproj%20%22k8s.gcr.io%22&type=code)
 - [ ] [Armada](https://github.com/G-Research) | [search query](https://github.com/search?q=org%3AG-Research%20%22k8s.gcr.io%22&type=code)
 - [ ] [cert-manager](https://github.com/cert-manager) | [search query](https://github.com/search?q=org%3Acert-manager%20%22k8s.gcr.io%22&type=code)
 - [ ] [ChaosMesh](https://github.com/chaos-mesh) | [search query](https://github.com/search?q=org%3Achaos-mesh%20%22k8s.gcr.io%22&type=code)
 - [ ] [ChubaoFS](https://github.com/cubefs) | [search query](https://github.com/search?q=org%3Acubefs%20%22k8s.gcr.io%22&type=code)
 - [ ] [Cilium](https://github.com/cilium) | [search query](https://github.com/search?q=org%3Acilium%20%22k8s.gcr.io%22&type=code)
 - [ ] [Cloud Custodian](https://github.com/cloud-custodian) | [search query](https://github.com/search?q=org%3Acloud-custodian%20%22k8s.gcr.io%22&type=code)
 - [ ] [Cloud Development Kit for Kubernetes (cdk8s)](https://github.com/cdk8s-team) | [search query](https://github.com/search?q=org%3Acdk8s-team%20%22k8s.gcr.io%22&type=code)
 - [ ] [Confidential Containers](https://github.com/confidential-containers) | [search query](https://github.com/search?q=org%3Aconfidential-containers%20%22k8s.gcr.io%22&type=code)
 - [ ] [containerd](https://github.com/containerd) | [search query](https://github.com/search?q=org%3Acontainerd%20%22k8s.gcr.io%22&type=code)
 - [ ] [Contour](https://github.com/projectcontour) | [search query](https://github.com/search?q=org%3Aprojectcontour%20%22k8s.gcr.io%22&type=code)
 - [ ] [CoreDNS](https://github.com/coredns) | [search query](https://github.com/search?q=org%3Acoredns%20%22k8s.gcr.io%22&type=code)
 - [ ] [CRI-O](https://github.com/cri-o) | [search query](https://github.com/search?q=org%3Acri-o%20%22k8s.gcr.io%22&type=code)
 - [ ] [Crossplane](https://github.com/crossplane) | [search query](https://github.com/search?q=org%3Acrossplane%20%22k8s.gcr.io%22&type=code)
 - [ ] [Curve](https://github.com/opencurve) | [search query](https://github.com/search?q=org%3Aopencurve%20%22k8s.gcr.io%22&type=code)
 - [ ] [Dapr](https://github.com/dapr) | [search query](https://github.com/search?q=org%3Adapr%20%22k8s.gcr.io%22&type=code)
 - [ ] [DevStream](https://github.com/devstream-io) | [search query](https://github.com/search?q=org%3Adevstream-io%20%22k8s.gcr.io%22&type=code)
 - [ ] [Dragonfly](https://github.com/dragonflyoss) | [search query](https://github.com/search?q=org%3Adragonflyoss%20%22k8s.gcr.io%22&type=code)
 - [ ] [Emissary-ingress](https://github.com/Emissary-ingress) | [search query](https://github.com/search?q=org%3AEmissary-ingress%20%22k8s.gcr.io%22&type=code)
 - [ ] [External Secrets Operator](https://github.com/external-secrets) | [search query](https://github.com/search?q=org%3Aexternal-secrets%20%22k8s.gcr.io%22&type=code)
 - [ ] [Falco](https://github.com/falcosecurity) | [search query](https://github.com/search?q=org%3Afalcosecurity%20%22k8s.gcr.io%22&type=code)
 - [ ] [Flux](https://github.com/fluxcd) | [search query](https://github.com/search?q=org%3Afluxcd%20%22k8s.gcr.io%22&type=code)
 - [ ] [Helm](https://github.com/helm) | [search query](https://github.com/search?q=org%3Ahelm%20%22k8s.gcr.io%22&type=code)
 - [ ] [Inclavare Containers](https://github.com/inclavare-containers) | [search query](https://github.com/search?q=org%3Ainclavare-containers%20%22k8s.gcr.io%22&type=code)
 - [ ] [k3s](https://github.com/k3s-io) | [search query](https://github.com/search?q=org%3Ak3s-io%20%22k8s.gcr.io%22&type=code)
 - [ ] [k8gb](https://github.com/k8gb-io) | [search query](https://github.com/search?q=org%3Ak8gb-io%20%22k8s.gcr.io%22&type=code)
 - [ ] [karmada](https://github.com/karmada-io) | [search query](https://github.com/search?q=org%3Akarmada-io%20%22k8s.gcr.io%22&type=code)
 - [ ] [Keda](https://github.com/kedacore) | [search query](https://github.com/search?q=org%3Akedacore%20%22k8s.gcr.io%22&type=code)
 - [ ] [Keptn](https://github.com/keptn) | [search query](https://github.com/search?q=org%3Akeptn%20%22k8s.gcr.io%22&type=code)
 - [ ] [Knative](https://github.com/knative) | [search query](https://github.com/search?q=org%3Aknative%20%22k8s.gcr.io%22&type=code)
 - [ ] [Konveyor](https://github.com/konveyor) | [search query](https://github.com/search?q=org%3Akonveyor%20%22k8s.gcr.io%22&type=code)
 - [ ] [Krustlet](https://github.com/krustlet) | [search query](https://github.com/search?q=org%3Akrustlet%20%22k8s.gcr.io%22&type=code)
 - [ ] [kube-rs](https://github.com/kube-rs) | [search query](https://github.com/search?q=org%3Akube-rs%20%22k8s.gcr.io%22&type=code)
 - [ ] [KubeArmor](https://github.com/kubearmor) | [search query](https://github.com/search?q=org%3Akubearmor%20%22k8s.gcr.io%22&type=code)
 - [ ] [KubeEdge](https://github.com/kubeedge) | [search query](https://github.com/search?q=org%3Akubeedge%20%22k8s.gcr.io%22&type=code)
 - [ ] [Kubernetes](https://github.com/kubernetes) | [search query](https://github.com/search?q=org%3Akubernetes%20%22k8s.gcr.io%22&type=code)
 - [ ] [KubeVela](https://github.com/oam-dev) | [search query](https://github.com/search?q=org%3Aoam-dev%20%22k8s.gcr.io%22&type=code)
 - [ ] [KubeVirt](https://github.com/kubevirt) | [search query](https://github.com/search?q=org%3Akubevirt%20%22k8s.gcr.io%22&type=code)
 - [ ] [kubewarden](https://github.com/kubewarden) | [search query](https://github.com/search?q=org%3Akubewarden%20%22k8s.gcr.io%22&type=code)
 - [ ] [Kudo](https://github.com/kudobuilder) | [search query](https://github.com/search?q=org%3Akudobuilder%20%22k8s.gcr.io%22&type=code)
 - [ ] [Kuma](https://github.com/kumahq) | [search query](https://github.com/search?q=org%3Akumahq%20%22k8s.gcr.io%22&type=code)
 - [ ] [Kyverno](https://github.com/kyverno) | [search query](https://github.com/search?q=org%3Akyverno%20%22k8s.gcr.io%22&type=code)
 - [ ] [LitmusChaos](https://github.com/litmuschaos) | [search query](https://github.com/search?q=org%3Alitmuschaos%20%22k8s.gcr.io%22&type=code)
 - [ ] [Longhorn](https://github.com/longhorn) | [search query](https://github.com/search?q=org%3Alonghorn%20%22k8s.gcr.io%22&type=code)
 - [ ] [Meshery](https://github.com/meshery) | [search query](https://github.com/search?q=org%3Ameshery%20%22k8s.gcr.io%22&type=code)
 - [ ] [metal3-io](https://github.com/metal3-io) | [search query](https://github.com/search?q=org%3Ametal3-io%20%22k8s.gcr.io%22&type=code)
 - [ ] [Nocalhost](https://github.com/nocalhost) | [search query](https://github.com/search?q=org%3Anocalhost%20%22k8s.gcr.io%22&type=code)
 - [ ] [OPA](https://github.com/open-policy-agent) | [search query](https://github.com/search?q=org%3Aopen-policy-agent%20%22k8s.gcr.io%22&type=code)
 - [ ] [OpenCost](https://github.com/kubecost) | [search query](https://github.com/search?q=org%3Akubecost%20%22k8s.gcr.io%22&type=code)
 - [ ] [OpenEBS](https://github.com/openebs) | [search query](https://github.com/search?q=org%3Aopenebs%20%22k8s.gcr.io%22&type=code)
 - [ ] [OpenELB](https://github.com/kubesphere) | [search query](https://github.com/search?q=org%3Akubesphere%20%22k8s.gcr.io%22&type=code)
 - [ ] [OpenKruise](https://github.com/openkruise) | [search query](https://github.com/search?q=org%3Aopenkruise%20%22k8s.gcr.io%22&type=code)
 - [ ] [OpenTelemetry](https://github.com/open-telemetry) | [search query](https://github.com/search?q=org%3Aopen-telemetry%20%22k8s.gcr.io%22&type=code)
 - [ ] [OpenYurt](https://github.com/openyurtio) | [search query](https://github.com/search?q=org%3Aopenyurtio%20%22k8s.gcr.io%22&type=code)
 - [ ] [Operator Framework SDK & Operator Framework Lifecycle Manager](https://github.com/operator-framework) | [search query](https://github.com/search?q=org%3Aoperator-framework%20%22k8s.gcr.io%22&type=code)
 - [ ] [ORAS (OCI Registry as Storage)](https://github.com/oras-project) | [search query](https://github.com/search?q=org%3Aoras-project%20%22k8s.gcr.io%22&type=code)
 - [ ] [Piraeus-Datastore](https://github.com/piraeusdatastore) | [search query](https://github.com/search?q=org%3Apiraeusdatastore%20%22k8s.gcr.io%22&type=code)
 - [ ] [sealer](https://github.com/sealerio) | [search query](https://github.com/search?q=org%3Asealerio%20%22k8s.gcr.io%22&type=code)
 - [ ] [Skooner](https://github.com/skooner-k8s) | [search query](https://github.com/search?q=org%3Askooner-k8s%20%22k8s.gcr.io%22&type=code)
 - [ ] [SPIFFE & SPIRE](https://github.com/spiffe) | [search query](https://github.com/search?q=org%3Aspiffe%20%22k8s.gcr.io%22&type=code)
 - [ ] [SuperEdge](https://github.com/superedge) | [search query](https://github.com/search?q=org%3Asuperedge%20%22k8s.gcr.io%22&type=code)
 - [ ] [Telepresence](https://github.com/telepresenceio) | [search query](https://github.com/search?q=org%3Atelepresenceio%20%22k8s.gcr.io%22&type=code)
 - [ ] [Thanos](https://github.com/thanos-io) | [search query](https://github.com/search?q=org%3Athanos-io%20%22k8s.gcr.io%22&type=code)
 - [ ] [Virtual Kubelet](https://github.com/virtual-kubelet) | [search query](https://github.com/search?q=org%3Avirtual-kubelet%20%22k8s.gcr.io%22&type=code)
 - [ ] [Volcano](https://github.com/volcano-sh) | [search query](https://github.com/search?q=org%3Avolcano-sh%20%22k8s.gcr.io%22&type=code)
 - [ ] [VS Code Kubernetes Tools](https://github.com/vscode-kubernetes-tools) | [search query](https://github.com/search?q=org%3Avscode-kubernetes-tools%20%22k8s.gcr.io%22&type=code)
 - [ ] [wasmCloud](https://github.com/wasmcloud) | [search query](https://github.com/search?q=org%3Awasmcloud%20%22k8s.gcr.io%22&type=code)
 - [ ] [WasmEdge Runtime](https://github.com/wasmedge) | [search query](https://github.com/search?q=org%3Awasmedge%20%22k8s.gcr.io%22&type=code)

**Comment by akshat5302** [comment]
Hey @mrbobbytables I would love to work on this umbrella issue and will try to migrate as much `k8s.gcr.io` to `registry.k8s.io` 👍

**Comment by dims** [comment]
No need to ask, pick a couple of projects, leave a note here, and file PRs with them. Leaving a note here will ensure will ensure folks won't end up duplicating work

**Comment by mrbobbytables** [comment]
Just to echo what dims said, please feel free to take them on and reference this issue. One request for anyone tackling these issues is to please double check the changes. There are some things that a simple find/replace isn't quite the answer e.g. generated code.

**Comment by aniruddha2000** [comment]
I am currently looking at containerd, CoreDNS

**Comment by akshat5302** [comment]
I'm looking at Aeraki mesh,Akri, Antrea and Argo

**Comment by harshitasao** [comment]
I'm looking at cilium, litmuschaos, karmada, KubeArmor.

**Comment by RishabhKodes** [comment]
Hi @dims @mrbobbytables, sent the pr's for `kubevirt`, `meshery` and `thanosbench`.

**Comment by cpanato** [comment]
Hello fro the `Helm` most of the changes are in the `helm/charts` repo, and that is archived so we will not change anything there.

the only change required is done in this PR https://github.com/helm/helm/pull/11829

can you make that a check?


cc @mrbobbytables @jeefy

**Comment by mrbobbytables** [comment]
> Hello fro the `Helm` most of the changes are in the `helm/charts` repo, and that is archived so we will not change anything there.
> 
> the only change required is done in this PR [helm/helm#11829](https://github.com/helm/helm/pull/11829)
> 
> can you make that a check?
>

done 👍

**Comment by shikharcodes** [comment]
I'm currently looking at `OpenEBS`.

**Comment by DiptoChakrabarty** [comment]
I am looking at  `k3s` `kudo` and `keptn` and `telepresence`

**Comment by rayandas** [comment]
I am looking at `cert-manager`, `flux`, `knative`, `kuma` and `kyverno`

**Comment by kannon92** [comment]
Hello @mrbobbytables! Thank you for documenting these cases.  

I noticed that for Armada you are still using our old org domain and that issue points to a lot of code unrelated to Armada.  We moved the Armada project to armadaproject org and I did the search and I did not find any references to k8s.gcr.io:

https://github.com/search?q=org%3Aarmadaproject+%22k8s.gcr.io%22

I think you could mark the Armada one as complete!

**Comment by mrbobbytables** [comment]
Thanks @kannon92, I'll mark it off 👍 

 I got the org from the CNCF's projects.csv doc here: https://github.com/cncf/toc/blob/main/docs/PROJECTS.csv

It might be worth opening a PR to update it to reflect its current location.

**Comment by kannon92** [comment]
> Thanks @kannon92, I'll mark it off 👍
> 
> I got the org from the CNCF's projects.csv doc here: https://github.com/cncf/toc/blob/main/docs/PROJECTS.csv
> 
> It might be worth opening a PR to update it to reflect its current location.

Thank you for calling that out. I just opened up a PR to fix that.

**Comment by CIPHERTron** [comment]
Hey all, I'll be taking up `ChaosMesh`, `Cloud Development Kit for Kubernetes (cdk8s)`, `Crossplane`, `Falco`, and `Konveyor`

**Comment by CIPHERTron** [comment]
Hey all, I'll be taking up `Confidential Containers`, `Cloud Development Kit for Kubernetes (cdk8s)`, `Crossplane`, `Falco`, and `Konveyor`.

**Comment by letmerecall** [comment]
Taking it up for `dapr`.

**Comment by zaneb** [comment]
No changes needed for metal3-io. One is sample output in a blog post, the others in an archived repo.

**Comment by slamp** [comment]
For Argo there is already an issue opened: https://github.com/argoproj/argo-cd/pull/12362/commits

**Comment by ahmedwaleedmalik** [comment]
Hi folks, I looked into the following orgs:

- [Contour](https://github.com/projectcontour): will be covered through 
  - https://github.com/projectcontour/contour/pull/5166 
- [OpenCost](https://github.com/kubecost): will be covered through
  - https://github.com/kubecost/openshift-helm-chart/pull/17
- [Piraeus-Datastore](https://github.com/piraeusdatastore): will be covered through
  - https://github.com/piraeusdatastore/linstor-scheduler-extender/pull/7
- [SPIFFE & SPIRE](https://github.com/spiffe): not affected
- [Virtual Kubelet](https://github.com/virtual-kubelet): will be covered through
  - https://github.com/virtual-kubelet/azure-aci/pull/484
- [Volcano](https://github.com/volcano-sh): only an old fork for https://github.com/kubernetes/kube-state-metrics is affected that was last updated on Mar 1, 2021.
- [wasmCloud](https://github.com/wasmcloud): the affected repository is archived.

Will take a look at other affected spaces tomorrow as well.

**Comment by ahmedwaleedmalik** [comment]
- [Aaeraki-mesh](https://github.com/aeraki-mesh): N/A; only an old fork https://github.com/aeraki-mesh/istio is affected that was last updated on Sep 23, 2021.
- [ChubaoFS](https://github.com/cubefs):
  - https://github.com/cubefs/cubefs/pull/1806
  - https://github.com/cubefs/cubefs-csi/pull/82
  - https://github.com/cubefs/cubefs-helm/pull/23
  - We can skip the fork for rook https://github.com/cubefs/rook which was last updated on Oct 13, 2020.
- [Crossplane](https://github.com/crossplane): N/A; the affected repository is archived.
- [DevStream](https://github.com/devstream-io): N/A
- [Dragonfly](https://github.com/dragonflyoss: N/A but I made the changes anyways
  - https://github.com/dragonflyoss/Dragonfly2/pull/2186 
  - https://github.com/dragonflyoss/dragonfly-examples/pull/2
- [External Secrets Operator](https://github.com/external-secrets): These are packaged operators for OperatorHub. I'm not a fan of updating the hosted manifests directly unless the owners of those operators roll out a new release and add a new version in the repos.
- [Flux](https://github.com/fluxcd): N/A but I made the changes anyways
  - https://github.com/fluxcd/flux is archived
  -  https://github.com/fluxcd/image-reflector-controller/pull/358
- [Inclavare Containers](https://github.com/inclavare-containers): N/A; they are replacing `k8s.gcr.io/pause:3.5` with a custom image for containerd v1.5.3. 
- [KubeVela](https://github.com/oam-dev):  N/A; the affected repository is archived.
- [Kuma](https://github.com/kumahq): N/A; only an old fork https://github.com/kumahq/gateway-api is affected that has no commits on the fork.

**Comment by NitishKumar06** [comment]
I'm working for `Aeraki Mesh` , `Akri`

**Comment by ahmedwaleedmalik** [comment]
> I'm working for `Aeraki Mesh` , `Akri`

I don't think we need anything for `Aeraki Mesh`.

> [Aaeraki-mesh](https://github.com/aeraki-mesh): N/A; only an old fork https://github.com/aeraki-mesh/istio is affected that was last updated on Sep 23, 2021.

**Comment by CIPHERTron** [comment]
Hello folks, here is the list of PRs that I've made to the following orgs:
1. Confidential Containers
- https://github.com/confidential-containers/tests-CCv0/pull/1
- https://github.com/confidential-containers/cloud-api-adaptor/pull/621
- https://github.com/confidential-containers/operator/pull/161
2. Konveyor
- https://github.com/konveyor/tackle-keycloak-theme/pull/7
- https://github.com/konveyor/move2kube-website/pull/106
- https://github.com/konveyor/konveyor.github.io/pull/9
3. cdk8s
- https://github.com/cdk8s-team/cdk8s/pull/1205
- https://github.com/cdk8s-team/cdk8s-redis/pull/554
4. Crossplane - This org had only one affected repo which has been archived since June, 2022
5. Falco - This has already been completed by @cpanato

**Comment by lakshya8066** [comment]
I'll take up `Krustlet`, `Nocalhost`, `OpenELB`, `ORAS`

**Comment by Akshit42-hue** [comment]
I'm working on `KubeArmor`, `kubewarden`

**Comment by ArkaSaha30** [comment]
Hello @ahmedwaleedmalik, as per your suggestion

> [External Secrets Operator](https://github.com/external-secrets): These are packaged operators for OperatorHub. I'm not a fan of updating the hosted manifests directly unless the owners of those operators roll out a new release and add a new version in the repos.

Should we skip it for now? OR do we need to make further communications before we take an action?

**Comment by ahmedwaleedmalik** [comment]
> Hello @ahmedwaleedmalik, as per your suggestion
> 
> > [External Secrets Operator](https://github.com/external-secrets): These are packaged operators for OperatorHub. I'm not a fan of updating the hosted manifests directly unless the owners of those operators roll out a new release and add a new version in the repos.
> 
> Should we skip it for now? OR do we need to make further communications before we take an action?

I would recommend that we skip it. cc @mrbobbytables

**Comment by lakshya8066** [comment]
There seems to be no required changes for `ORAS` organization. The only repository that has `k8s.gcr.io` has been archived and is read-only.

**Comment by lakshya8066** [comment]
@mrbobbytables `OpenELB` is incorrectly linked to https://github.com/kubesphere
There should be a separate entry for `Kubesphere` with search query link: https://github.com/search?q=org%3Akubesphere%20%22k8s.gcr.io%22&type=code
OpenELB link: https://github.com/openelb
OpenELBsearch query link: https://github.com/search?q=org%3AOpenELB+%22k8s.gcr.io%22&type=code

**Comment by mrbobbytables** [comment]
> @mrbobbytables `OpenELB` is incorrectly linked to https://github.com/kubesphere There should be a separate entry for `Kubesphere` with search query link: https://github.com/search?q=org%3Akubesphere%20%22k8s.gcr.io%22&type=code OpenELB link: https://github.com/openelb OpenELBsearch query link: https://github.com/search?q=org%3AOpenELB+%22k8s.gcr.io%22&type=code

Thanks - I got the location from the CNCF project list:
https://github.com/cncf/toc/blob/main/docs/PROJECTS.csv

Would probably be worth updating that to point to the right location for OpenELB

**Comment by ahmedwaleedmalik** [comment]
Hey folks, just an update:

- [Argo](https://github.com/argoproj):
   -  https://github.com/argoproj/argo-workflows/pull/10891
   - https://github.com/argoproj/gitops-engine/pull/518
- [Cloud Development Kit for Kubernetes (cdk8s)](https://github.com/cdk8s-team): 
    -  https://github.com/cdk8s-team/cdk8s-core/pull/1172
- [k8gb](https://github.com/k8gb-io): Done
- [Knative](https://github.com/knative):
      - https://github.com/knative/operator/pull/1342
      - https://github.com/knative-sandbox/eventing-rabbitmq/pull/1100
      - https://github.com/knative-sandbox/sample-source/pull/468
      - https://github.com/knative-sandbox/eventing-github/pull/376
      - https://github.com/knative-sandbox/eventing-kogito/pull/244
      - https://github.com/knative-sandbox/eventing-ceph/pull/328
      - https://github.com/knative-sandbox/eventing-redis/pull/441
- [Krustlet](https://github.com/krustlet): N/A
- [KubeArmor](https://github.com/kubearmor): N/A; only an old fork https://github.com/kubearmor/minikube is affected.
- [kube-rs](https://github.com/kube-rs): N/A
- [Kudo](https://github.com/kudobuilder):
   - https://github.com/kudobuilder/kudo/pull/1818
- [kubewarden](https://github.com/kubewarden): Done
- [LitmusChaos](https://github.com/litmuschaos):
    - https://github.com/litmuschaos/litmus/pull/3945
- [OpenCost](https://github.com/kubecost): Done; remaining affected projects are not maintained anymore.
- [Nocalhost](https://github.com/nocalhost): N/A
- [OpenKruise](https://github.com/openkruise): 
    - https://github.com/openkruise/samples/pull/6 
- [OpenYurt](https://github.com/openyurtio):
     - https://github.com/openyurtio/openyurt.io/pull/306
     - https://github.com/openyurtio/yurt-app-manager/pull/142
     - https://github.com/openyurtio/yurt-dashboard/pull/40
- [Operator Framework SDK & Operator Framework Lifecycle Manager](https://github.com/operator-framework): Done
- [SuperEdge](https://github.com/superedge): 
   - https://github.com/superedge/edgeadm/pull/44
- [Virtual Kubelet](https://github.com/virtual-kubelet): Done
- [VS Code Kubernetes Tools](https://github.com/vscode-kubernetes-tools): Pending PR is approved now and should be merged soon.

Had to take over a few subtasks(organizations) since they were stalled for quite some time.

**Comment by ameukam** [comment]
@mrbobbytables are we still doing this ? If no maybe we can close ?

**Comment by BenTheElder** [comment]
Note: With the GRC team's help we are keeping a redirect in place for the immediate future, HOWEVER: users should switch to registry.k8s.io as soon as possible, it is the canonical host, k8s.gcr.io redirects there anyhow, and there's no guaranteed timeline for sustaining k8s.gcr.io, the redirect was initially meant as a temporary measure to ease the transition.

See also: https://registry.k8s.io#stability and related docs.

**Comment by ayia-hosni** [comment]
I have updated the remaining registry references in the argoproj/argo-cd installation manifests.

You can track the progress here:
https://github.com/argoproj/argo-cd/pull/25802
