### ISSUE TITLE
AWS: Identity service quotas changes needed for scalability jobs

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#5071]
```[tasklist]
### Tasks
- [x] Identity what service quotas need to set
- [x] Create a dedicatet pool of AWS accounts for scalability tests: https://github.com/kubernetes/k8s.io/pull/5298
- [ ] Add pool to boskos
```

/sig scalability
/area infra
/area infra/aws
/milestone v1.28
/priority important-soon

**Comment by ameukam** [comment]
I suspect we'll need to bump quotas for:
- ec2
- ebs
- vpc

**Comment by ashishranjan738** [comment]
Hi All, please find the ec2 instance types that we can use. 
```
```

**Comment by shyamjvs** [comment]
@ashishranjan738 Thanks! Can you also gather these:
- API rate limit increases needed (mainly ec2, IAM and STS)
- VPC-related account limits we have on our internal scale tests

**Comment by shyamjvs** [comment]
> InstanceType List: c5.large m5.large r5.large t3.large t3a.large c5a.large m5a.large r5a.large

This is a good list of instance-types to begin with. But as we scale-up the job, we should see if we can switch to mediums/smalls to save a bunch of cost.

**Comment by ashishranjan738** [comment]
> @ashishranjan738 Thanks! Can you also gather these:
> 
> * API rate limit increases needed (mainly ec2, IAM and STS)
> * VPC-related account limits we have on our internal scale tests

Pasting the limits EC2 and VPC:
```
VPC
----
Egress-only internet gateways per Region 500
Internet gateways per Region 500
IPv4 CIDR blocks per VPC 50
NAT gateways per Availability Zone 100
Network interfaces per Region 20000
Participant accounts per VPC 200
Routes per route table 1000
Subnets that can be shared with an account 200
VPC security groups per Region 10000
VPCs per Region 500

EC2
---
Concurrent client connections per Client VPN endpoint 126,000
EC2-VPC Elastic IPs 1000
Multicast Network Interfaces per transit gateway 10000
```

**Comment by ameukam** [comment]
Those values are already applied by default:

```
Concurrent client connections per Client VPN endpoint 126,000
Multicast Network Interfaces per transit gateway 10000
```

**Comment by ameukam** [comment]
According to https://docs.aws.amazon.com/general/latest/gr/sts.html, There is no need to raise quota for:

> STS API Call TPS: 3000

**Comment by ameukam** [comment]
@ashishranjan738 can you provide the service code for those:

```
DescribeInstances (expected 25 qps on avg)
AssignPrivateIpAddresses (expected 25 qps on avg)
DescribeNetworkInterface (expected 25 qps on avg)
CreateNetworkInterface (expected 3 qps on avg)
AttachNetworkInterface (expected 3 qps on avg)
```

I can't easily find them on the Service Quota console.

**Comment by ashishranjan738** [comment]
Update: I have raised an internal AWS ticket to increase these limits. Its pending on Approval from stake holders. Will update this thread once it is done.

**Comment by ashishranjan738** [comment]
Update: Got a confirmation that the quotas has been successfully applied for the scale test accounts.

**Comment by dims** [comment]
related https://github.com/kubernetes/k8s.io/issues/5715

**Comment by hakman** [comment]
> Hi All, please find the ec2 instance types that we can use.
> 
> ```
> InstanceType List: c5.large m5.large r5.large t3.large t3a.large c5a.large m5a.large r5a.large
> ```

@ashishranjan738 Could we also use `m6g` and `c6g` instance types?
