### ISSUE TITLE
eks-prow-build-cluster: Monitoring solution

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/k8s.io#5165]
We have a simple monitoring solution based on Prometheus and Grafana in eks-prow-build-cluster. However, that monitoring stack is not exposed at all and we should look into unifying monitoring for GKE and EKS clusters.

```[tasklist]
### Tasks
- [x] Initial monitoring stack for eks-prow-build-cluster
- [x] Considering deploying node-problem-detector (npd)
- [x] Expose the monitoring stack (e.g. Grafana) so it can be accessed publicly
- [ ] Integrate the existing GKE monitoring stack with the new monitoring stack
```

/priority important-longterm

**Comment by memetics19** [comment]
@xmudrii  Can i pickup this ?

**Comment by xmudrii** [comment]
@memetics19 As far as I know @wozniakjan is already working on this.
/assign @wozniakjan

**Comment by wozniakjan** [comment]
hey, yeah thanks for assigning. I haven't found the time yet but next week should finally have the capacity to move this forward.

**Comment by wozniakjan** [comment]
> - [ ] Considering deploying node-problem-detector (npd)

PR under review https://github.com/kubernetes/k8s.io/pull/5291

**Comment by xmudrii** [comment]
@wozniakjan I think we can get a dedicated domain for it.

**Comment by wozniakjan** [comment]
> Expose the monitoring stack (e.g. Grafana) so it can be accessed publicly

draft PR https://github.com/kubernetes/k8s.io/pull/5316, figuring out how to TLS

**Comment by wozniakjan** [comment]
> - [ ] Integrate the existing GKE monitoring stack with the new monitoring stack

@xmudrii, @ameukam is this the GKE monitoring stack mentioned above?https://github.com/kubernetes/k8s.io/tree/main/infra/gcp/terraform/k8s-infra-monitoring
I guess it's https://cloud.google.com/monitoring, correct?

I will take a look if there are any tools to aggregate GCP cloud monitoring with the self-hosted Prometheus we use in AWS. Judging from the wording of the task, it's desired to display GCP metrics in the AWS Prometheus, not the other way around.

**Comment by ameukam** [comment]
This is i

> > * [ ]  Integrate the existing GKE monitoring stack with the new monitoring stack
> 
> @xmudrii, @ameukam is this the GKE monitoring stack mentioned above?https://github.com/kubernetes/k8s.io/tree/main/infra/gcp/terraform/k8s-infra-monitoring I guess it's https://cloud.google.com/monitoring, correct?
> 
> I will take a look if there are any tools to aggregate GCP cloud monitoring with the self-hosted Prometheus we use in AWS. Judging from the wording of the task, it's desired to display GCP metrics in the AWS Prometheus, not the other way around.

This is inaccurate. This link you provided is only for specific resources and not related the build clusters. 

We already aggregate metrics in https://monitoring.prow.k8s.io. we can find resources for this monitoring stack here:https://github.com/kubernetes/test-infra/tree/master/config/prow/cluster/monitoring

**Comment by wozniakjan** [comment]
> We already aggregate metrics in https://monitoring.prow.k8s.io

that is perfect, thank you very much!

**Comment by wozniakjan** [comment]
increased parity between GKE and EKS grafana is getting merged in https://github.com/kubernetes/k8s.io/pull/5324.

However, after https://github.com/kubernetes/k8s.io/pull/5316 merged, a side quest popped up. There is a desire to restrict some boards for public access. Namely, https://monitoring-eks.prow.k8s.io/d/node-exporter-full/node-exporter-full is considered to be potentially oversharing. There was also a valid opinion that this dashboard could be very useful and we shouldn't get rid of it entirely. @pkprzekwas and I had the following idea:
1) create a public org with a view for only a subset of dashboards that are considered fully public and safe
2) change the unauthenticated anonymous to that org
3) keep the too-sensitive boards visible only for the authenticated users in the original grafana org.

**Comment by wozniakjan** [comment]
> There is a desire to restrict some boards for public access. Namely, https://monitoring-eks.prow.k8s.io/d/node-exporter-full/node-exporter-full is considered to be potentially oversharing.

disabling sensitive boards in https://github.com/kubernetes/k8s.io/pull/5387

**Comment by wozniakjan** [comment]
> - [ ] Integrate the existing GKE monitoring stack with the new monitoring stack

@pkprzekwas @xmudrii, I got a much easier idea about monitoring integration than Prometheus remote-write capability. How about we just embed grafana dashboards as iframes?

Given anonymous access is enabled (for readonly) on both, we could just set this on the exporting dashboard:
```ini
[security]
allow_embedding = true
```
and on the importing dashboard (the single pane of glass) set this:
```ini
[panels]
disable_sanitize_html = true
```

the independent panels can be then integrated as iframes, for example:
```json
{
  "type": "text",
  "content": "<iframe src=\"https://monitoring-eks.prow.k8s.io/d-solo/g4Okc0_4k/boskos-server-dashboard?orgId=1&panelId=2\" width=\"450\" height=\"200\" frameborder=\"0\"></iframe>",
  "mode": "html"
}
```

we wouldn't be able to query across multiple clusters but it could be ok step to just see what is going on.

**Comment by wozniakjan** [comment]
https://github.com/kubernetes/test-infra/pull/29920 proposing to allow dashboard embedding, let's see how that goes.

**Comment by xmudrii** [comment]
Most of tasks are done. We're yet to come up with a single plane of glass monitoring solution, but I'll create a new issue to track that
/close
