### ISSUE TITLE
eks-prow-build-cluster: Costs optimization

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/k8s.io#5167]
We didn't pay much attention to optimizing costs while building eks-prow-build-cluster, but we should eventually do so. There are some steps that we can take to reduce costs short-term and long-term.

```[tasklist]
### Tasks
- [ ] https://github.com/kubernetes/k8s.io/issues/5168
- [ ] #5066
- [ ] #4928
- [ ] Reduce spent either on SSDs or provisioned IOPS
- [ ] Look into reducing spent on NAT Gateway and other networking related costs
```

/priority important-longterm
