### ISSUE TITLE
[Umbrella issue] cleanup AWS organization

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#5844]
Since we created the AWS organization for the Kubernetes project, we migrated and create a bunch of AWS accounts.
Some of them are unused or contains unused resources. We should delete those unused for the last 6 months.

Accounts migrated:
  - https://github.com/kubernetes/k8s.io/issues/4626
  
Accounts groups:
  - [x] e2e-kops-*: https://github.com/kubernetes/kops/issues/15912
  - [x] capa-2020-*: https://github.com/kubernetes/k8s.io/issues/5914
  - [x] image-builder-aws-*: https://github.com/kubernetes/k8s.io/issues/5855

**Comment by michaelssingh** [comment]
Happy to take this issue

**Comment by ameukam** [comment]
> Happy to take this issue

Unfortunately, this requires advanced access to the AWS organization.

**Comment by ameukam** [comment]
We are done. Most of the unused accounts have been deleted. 
We should revisit those remaining for closing before EOY.

/close
