### ISSUE TITLE
GCP: setup infrastructure for dl.k8s.io

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#5967]
Part of:
 - https://github.com/kubernetes/k8s.io/issues/2396
 
 This is mostly an effort to setup a new community-owned storage backend that will act as the replacement of `gs://kubernetes-release` and the new origin for the Fastly service (`cdn.dl.k8s.io`).
 
This give us also to the opportunity get some visibility on the egress cost generated by the Fastly service. We could also compare bandwith between this new bucket and `gs://kubernetes-release`. 
```[tasklist]
### Tasks
- [x] Setup a prod project on GCP (and possibly a sandbox/staging env)
- [x] Setup a regional bucket for the binaries
- [x] Ensure binaries are synced from gs://kubernetes-release to the new bucket
```

**Comment by ameukam** [comment]
cc @BenTheElder 

/milestone v1.29
/priority important-soon
/kind feature
/area infra/gcp

**Comment by BenTheElder** [comment]
To further elaborate:

Since tagged kubernetes releases only happen ~monthly and are the only time new content is written to the bucket: We can test this in-between k8s patch release cycles once we have a synced trusted copy provided by k8s infra instead of the ancient google.com bucket.

The new bucket can be setup as a cached copy of the original bucket, and we can temporarily switch fastly to point to this as the backend and rollback if there are issues or otherwise after a period of say 1 week for bandwidth, cost, etc. data collection.

Then when this is proven out we can look at ensuring krel/releng has IAM to push direct to the new bucket and attempt a full migration, knowing that the read-only traffic-serving aspect is already good to go.

**Comment by michaelssingh** [comment]
I can take a stab at this

**Comment by bertusdev** [comment]
how can I take this task?

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/k8s.io/pull/6008

The manual actions to sync the bucket etc need to be pretty highly trusted (because the contents need to be trusted and k8s release binaries are not currently signed...), this is not a great first task.

https://github.com/kubernetes/k8s.io/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by ameukam** [comment]
Most of the required work here is done. The last piece is to automate:
> The manual actions to sync the bucket etc need to be pretty highly trusted

**Comment by michaelssingh** [comment]
> Most of the required work here is done. The last piece is to automate:
> 
> > The manual actions to sync the bucket etc need to be pretty highly trusted

& what does that look like?

**Comment by michaelssingh** [comment]
> xref: #6008
> 
> The manual actions to sync the bucket etc need to be pretty highly trusted (because the contents need to be trusted and k8s release binaries are not currently signed...), this is not a great first task.
> 
> https://github.com/kubernetes/k8s.io/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

What are you even saying?
It sounds like, these actions need to be done by trusted individuals, but if the release binaries aren't signed, then there are no trusted individuals.

**Comment by BenTheElder** [comment]
> It sounds like, these actions need to be done by trusted individuals, but if the release binaries aren't signed, then there are no trusted individuals and no trusted content.

No, we have trusted individuals within the project, e.g. the steering committee, release leads, k8s infra TLs.

k8s-infra  Tech Leads are trusted with full break-glass access to the entire infrastructure on all cloud accounts and can be trusted to do the data sync. Steering or release leads would also suffice.

It would be preferable to at least have that level of trust for populating the bucket. Alternatively if we didn't trust those people we'd probably automate it, but that's unnecessary extra work here for a one-time sync that would be enabled by those some people anyhow.

https://github.com/kubernetes/k8s.io/pull/6008 did most of the implementation work on this issue.

**Comment by ameukam** [comment]
I think we can call this done. 

binaries are synced from `gs://kubernetes-release` to a community-owned bucket. 

/close
