### ISSUE TITLE
eks-prow-build-cluster: Replace FluxCD with ArgoCD

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/k8s.io#6442]
It has been discussed to replace FluxCD that we use for eks-prow-build-cluster with ArgoCD. ArgoCD offers many more features that can help us to easier manage all our clusters (e.g. UI, terminal/console, easier to debug issues...).

```[tasklist]
### Tasks
- [ ] Investigate what does it take to replace FluxCD with ArgoCD and come up with a proposal
- [ ] Investigate multi-cluster setup for ArgoCD (e.g. so that we can manage both GKE and EKS clusters with it)
- [ ] Set up a new cluster to host ArgoCD and the monitoring stack
- [ ] Deploy ArgoCD
- [ ] Migrate eks-prow-build-cluster from FluxCD to ArgoCD
```

/assign @xmudrii @koksay
/sig k8s-infra
/area infra infra/aws
/milestone v1.30
/priority important-soon

**Comment by ameukam** [comment]
/milestone clear

@koksay what's the status of this ?

**Comment by xmudrii** [comment]
@ameukam We don't have access to ArgoCD at the moment. I'll figure this out with @upodroid
