### ISSUE TITLE
Umbrella Issue: Kubernetes Infrastructure Tech Debt

### ISSUE THREAD

**Issue by upodroid** [kubernetes/k8s.io#6608]
This is a bunch of technical debt in our Infra that needs to be resolved in the future.

```[tasklist]
### IaC(Infrastructure as Code)
- [ ] Manage DNS via Terraform instead of Octodns
- [ ] Rewrite the bash scripts at https://github.com/kubernetes/k8s.io/tree/main/infra/gcp/bash as terraform
- [ ] Enable Terraform self-service for changes with [Atlantis](https://www.runatlantis.io/)
```

```[tasklist]
### Kubernetes
- [ ] Recreate the GKE clusters on custom networks
- [ ] Create a doc with IP allocations for our infra across multiple cloud platforms to avoid IP overlap issues. We need to connect our EKS build cluster to a VMware Private Cloud network so our IP space needs to be properly carved out and documented.
- [ ] https://github.com/kubernetes/k8s.io/issues/6442
- [ ] Consolidate all the Kubernetes manifests that will be used by ArgoCD in one location
- [ ] https://github.com/kubernetes/k8s.io/issues/5110
```

Please edit this issue with other technical debts that we have.

**Comment by BenTheElder** [comment]
> Manage DNS via Terraform instead of Octodns

So taking this as an example, I don't think we should just declare this tech-debt without more details outlining why this is bad and why the alternative is better.

AFAICT our DNS utils are working great, they're relatively small and yaml is familiar to our community at large more than terraform.

This tool doesn't have any external state and does a reliable, kubernetes style "reconcile desired state versus the world", and we have some other neat tricks built in e.g. to staging deploy and test that first.

> Rewrite the bash scripts at https://github.com/kubernetes/k8s.io/tree/main/infra/gcp/bash as terraform

Similarly, some of the bash scripts may be tech debt, but terraform isn't free to maintain either and we haven't had problems with most of these.

In general this checklist seems pretty opinionated without justifications.

**Comment by xmudrii** [comment]
I think at least some of items are done, but we should check and update.
/remove-lifecycle rotten
