### ISSUE TITLE
Turn down kubernetes-tools/tools-cluster cluster

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#790]
We can do this once:
- [x] slack-event-log has been migrated (#751)
- [x] slack-moderator has been migrated (#751)
- [x] slack-welcomer has been migrated (#751)
- [x] slackin has been migrated (#751)
- [x] @spiffxp has confirmed there's really nothing left on this cluster

/wg k8s-infra
/area cluster-mgmt
/assign @spiffxp

**Comment by spiffxp** [comment]
We want to wait two more weeks before doing this. Leaving old apps up for now just in case we need to switch DNS over

**Comment by spiffxp** [comment]
Bart to confirm with slack admins

**Comment by bartsmykla** [comment]
[Wrote at the #slack-admins channel](https://kubernetes.slack.com/archives/C4M06S5HS/p1589387863130600). Let's wait 24h and I think we'll be ready to turn down the cluster if there won't be any objections

**Comment by spiffxp** [comment]
Deleting the cluster

**Comment by spiffxp** [comment]
/close
Cluster has been turned down

We'll need to keep the kubernetes-tools project around until https://github.com/kubernetes/k8s.io/issues/905 is resolved
